# app.toml: app main conf
 
# can be read by env.AppName() method
APPName = "go-liziwei01-library"
 
# run mod
# debug    : corresponds to env.RunModeDebug
# test     : corresponds to env.RunModeTest
# release  : corresponds to env.RunModeRelease
# can be read by env.RunMode()
RunMode = "test"
 
# conf of HTTPServer 
[HTTPServer]
 
# http server listening port
# meaning of {env.LISTEN_PORT|8080}:
# try to read key=LISTEN_PORT from env. default 8080
# when publish, I use {env.LISTEN_PORT|NoPort}
# Listen="0.0.0.0:NoPort", net.Listen will report error even if have not check the format
# 0.0.0.0 represent all of the ip address locally，can be access by localhost
#Listen="0.0.0.0:{env.LISTEN_PORT|NoPort}"
Listen="0.0.0.0:{env.LISTEN_PORT|8080}"

# ms, optional
ReadTimeout=1000
 
# ms, optional
# should be the longest acceptable time
# middleware should not be longger
WriteTimeout=40000 # 40s
 
# ms, optional
IdleTimeout=1000
