ak = "AKIAXLWQPQRES3ACBVGU"
sk = "BIAp0FGidtXu/W36NcWiDSM7XcB9h6iHiw5wU7LttVA4"
region = "us-east-2"
sesMail = "alssylk@gamil.com"

[workmail]
server = ""
port = 587
pwd = ""
user = "alssylk@gmail.com"
